# TODO: COPY THIS OVER TO docker-compose.local.yml FOR YOUR OWN LOCAL CONFIG
version: "3"

services:

  integration_tests:
    volumes:
      - ./:/mnt/integration-tests/
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - docker-compose.env

  microservices:
    image: <AWS_CI_AWS_ACCOUNT_ID>.dkr.ecr.us-east-2.amazonaws.com/optimism/rollup-microservices:latest
    volumes:
      - l1-node-data:/mnt/l1-node:rw
      - l2-node-data:/mnt/l2-node:rw
    env_file:
      - docker-compose.env

  l1_chain:
    image: trufflesuite/ganache-cli:latest
    entrypoint: node /app/ganache-core.docker.cli.js -p 9545 --account="df8b81d840b9cafc8cd68cf94f093726b174b5f109eba11a3f2a559e5f9e8bce,100" --account="06caa6f48604a58872e27db8c2980584e20faab37613f51383bb5be62db80c50,100"
    ports:
      - 9545:9545

  postgres:
    image: <AWS_CI_AWS_ACCOUNT_ID>.dkr.ecr.us-east-2.amazonaws.com/optimism/postgres:latest
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - 5432:5432

  geth_l2:
    image: <AWS_CI_AWS_ACCOUNT_ID>.dkr.ecr.us-east-2.amazonaws.com/optimism/geth:latest
    volumes:
      - l2-node-data:/mnt/l2-node/l2:rw
    environment:
      - CLEAR_DATA_KEY
      - TARGET_GAS_LIMIT
      - VOLUME_PATH=/mnt/l2-node/l2
      - HOSTNAME=geth_l2
      - PORT=8545
      - NETWORK_ID=108
    ports:
      - 8545:8545

volumes:
  l1-node-data:
  l2-node-data:








